name: CI/CD s3 

on:
  push:
    branches: [""]

jobs:
  build:
    runs-on: ubuntu-latest
    
    
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}

      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - run: npm i

    - run: |
        touch .env.local
        echo "${{ secrets.PROD_ENV_FILE }}" > .env.local

    - run: npm run build --if-present

    - name: Save Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Frontend-latest
        path: /

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}
        aws-region: ca-central-1

    - name: Upload file to S3
      run: |
       aws s3 cp /Frontend-latest s3://ambel-build-files/Frontend-latest