apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-actions
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-binding
subjects:
- kind: ServiceAccount
  name: github-actions
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io



---

#Custom Role

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: my-namepace
  name: custom-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["list"]
 

---
#Applying the custom roles binding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-actions-binding
  namespace: my-namepace
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: kube-system
roleRef:
  kind: Role
  name: custom-role
  apiGroup: rbac.authorization.k8s.io


---
#ClusterRole for Cluster-Wide Permissions

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-clusterrole
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "namespaces"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["get", "list"]

---

#apply the cluster role

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: github-actions-clusterrole-binding
subjects:
  - kind: ServiceAccount
    name: github-actions
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: custom-clusterrole
  apiGroup: rbac.authorization.k8s.io

