
# scheduled-backup.yaml
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-scheduled-backup
spec:
  schedule: "0 */6 * * *"
  cluster:
    name: postgres-cluster
  immediate: false
