# There are two different file System
# 1. local
# 2. Network

# Based on your cloud provider you can configure the kubenatics cluster with any of the following configuration

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - noatime
  - nodiratime
  - data=ordered