# monitoring-config.yaml

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-monitor
spec:
  selector:
    matchLabels:
      postgresql: postgres-cluster
  podMetricsEndpoints:
  - port: metrics
    interval: 30s

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: postgres-alerts
spec:
  groups:
  - name: postgresql
    rules:
    - alert: PostgreSQLHighReplicationLag
      expr: pg_replication_lag_bytes > 100000000
      for: 5m
      labels:
        severity: critical
    - alert: PostgreSQLHighConnections
      expr: pg_stat_activity_count > 100
      for: 5m
      labels:
        severity: warning
    - alert: PostgreSQLSlowQueries
      expr: pg_stat_activity_duration_seconds_avg > 3
      for: 5m
      labels:
        severity: warning
    - alert: PostgreSQLLongRunningQueries
      expr: pg_stat_activity_duration_seconds_avg > 3
      for: 1m
      labels:
        severity: critical
