# postgres-operator-cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: postgres
spec:
  enableSuperuserAccess: true
  instances: 3
  imageName: "ghcr.io/cloudnative-pg/postgresql:17.2"

  # PostgreSQL configuration
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "1GB"
      effective_cache_size: "2GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "250"
      work_mem: "2621kB"
      min_wal_size: "1GB"
      max_wal_size: "2GB"
      max_wal_senders: "3"
      max_replication_slots: "3"
      wal_level: "logical"

  replicationSlots:
    highAvailability:
      enabled: true
      
  bootstrap:
    recovery:
      source: postgres-cluster

  primaryUpdateStrategy: unsupervised
  synchronousReplication:
    enabled: true
    
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname

  # Storage configuration
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: local-storage
      volumeMode: Filesystem

  # Resource requirements
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1"

   # Backup configuration
  backup:
    barmanObjectStore:
      destinationPath: "s3://ambel-backup/postgresql"
      endpointURL: "https://s3.amazonaws.com"
      s3Credentials:
        accessKeyId:
          name: aws-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: aws-creds
          key: SECRET_ACCESS_KEY

  # Monitoring configuration
  monitoring:
    enablePodMonitor: true


