apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  labels:
    type: redis-storage
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany #or ReadWriteOnce, If neeed to access via single POD or Node at a timee
  hostPath:
    path: /mnt/data/redis
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: redis-storage
