apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    appendonly yes
    bind 127.0.0.1 ::1 #0.0.0.0 If need to access outside of the k8s cluster or outsude application.
    protected-mode no
    maxmemory 1gb
    maxmemory-policy allkeys-lru
