grafana:
  fullnameOverride: grafana
  service:
    type: ClusterIP
  ingress:
    enabled: true
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /
    hosts:
      - monitoring.ambel.co
    tls:
      - hosts:
          - monitoring.ambel.co
        secretName: ambel.co-grafana-tls

prometheus:
  fullnameOverride: prometheus
  service:
    type: ClusterIP
  ingress:
    enabled: false
  prometheusSpec:
    externalUrl: "http://prometheus.monitoring.svc.cluster.local:9090"

