apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongos
  namespace: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongos
  template:
    metadata:
      labels:
        app: mongos
    spec:
      containers:
      - name: mongos
        image: mongo:6.0
        command: ["mongos"]
        args:
        - "--configdb=cfg0/mongodb-0.mongodb.db.svc.cluster.local:27017,mongodb-1.mongodb.db.svc.cluster.local:27017,mongodb-2.mongodb.db.svc.cluster.local:27017"
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongos
  namespace: db
spec:
  type: LoadBalancer
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongos
