apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: db
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
---
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: db
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>
