apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: db
spec:
  serviceName: postgresql
  replicas: 3
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      securityContext:
        fsGroup: 999
      initContainers:
        - name: fix-permissions
          image: busybox:1.35.0-uclibc
          command: ["sh", "-c", "chown -R postgres:postgres /var/lib/postgresql/data"]
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgresql
          image: postgres:latest
          command: ["postgres"]
          args:
            - "-c"
            - "ssl=on"
            - "-c"
            - "ssl_cert_file=/etc/ssl/certs/postgresql.crt"
            - "-c"
            - "ssl_key_file=/etc/ssl/certs/postgresql.key"
            - "-c"
            - "ssl_ca_file=/etc/ssl/certs/ca.crt"
            - "-c"
            - "config_file=/etc/postgresql/postgresql.conf"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: password
          volumeMounts:
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: postgresql-config
              mountPath: /etc/postgresql
              readOnly: true
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
          securityContext:
            runAsUser: 999
            runAsGroup: 999
      volumes:
        - name: ssl-certs
          secret:
            secretName: postgresql-ssl-secret
        - name: postgresql-config
          configMap:
            name: postgresql-config
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
        namespace: db
        labels:
          app: postgresql
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: standard
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: db
spec:
  clusterIP: None
  selector:
    app: postgresql
  ports:
    - port: 5432
      targetPort: 5432
