apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: default
spec:
  limits:
    - max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
      type: Container
