#1st volume for logs and data
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
      type: data
  name: data-volume-0
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongodb-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-2

---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
      type: logs
  name: logs-volume-0
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongodb-0-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-2

# ---
# #2nd volume for logs and data

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#       type: data
#   name: data-volume-1
#   namespace: mongodb
# spec:
#   capacity:
#     storage: 8Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   hostPath:
#     path: /mnt/data/mongodb-1
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - worker-1

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   labels:
#       type: logs
#   name: logs-volume-1
#   namespace: mongodb
# spec:
#   capacity:
#     storage: 8Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   hostPath:
#     path: /mnt/data/mongodb-1-1
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values:
#                 - worker-1

---
#3rd volume for logs and data

apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
      type: data
  name: data-volume-2
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongodb-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
      type: logs
  name: logs-volume-2
  namespace: mongodb
spec:
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/mongodb-2-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker-1