apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-0
  namespace: postgres
  # labels:
  #   app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-a

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-1
  namespace: postgres
  # labels:
  #   app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-b

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-2
  namespace: postgres
  # labels:
  #   app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-c