apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-0
  namespace: db
  labels:
    app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-1
  namespace: db
  labels:
    app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-1

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv-2
  namespace: db
  labels:
    app: postgresql
spec:
  capacity:
    storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /mnt/data/postgresql-2