apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  kafka:
    version: 3.9.0
    replicas: 1
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9093
        type: loadbalancer
        tls: false
        configuration:
          externalTrafficPolicy: Local
#     - name: external
#       port: 9093
#       type: ingress
#       tls: true
#       configuration:
#         bootstrap:
#           host: kafka.ambel.co
#          annotations:
#           external-dns.alpha.kubernetes.io/hostname: kafka.ambel.co.
#           external-dns.alpha.kubernetes.io/ttl: "60"
#         brokers:
#         - broker: 0
#           host: broker-0.kafka.ambel.co
#           annotations:
#             external-dns.alpha.kubernetes.io/hostname: broker-0.kafka.ambel.co.
#             external-dns.alpha.kubernetes.io/ttl: "60"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      log.retention.hours: 72
      log.segment.bytes: 1073741824
      log.retention.bytes: 25737418240
      max.message.bytes: 10485760
      inter.broker.protocol.version: "3.9"
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
    jvmOptions:
      -Xms: "512m"
      -Xmx: "1g"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 30Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"