apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.9.0
  replicas: 1
  #image: tazul96/kafka-connect-custom:3.9.0
  bootstrapServers: kafka-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: tazul96/kafka-connect-custom:3.9.0
      pushSecret: dockerhub-secret
    plugins:
      - name: mongodb-connector
        artifacts:
          - type: zip
            url: https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.11.0/mongo-kafka-connect-1.11.0.zip
      - name: postgresql-connector
        artifacts:
          - type: jar
            url: https://jdbc.postgresql.org/download/postgresql-42.7.3.jar
  config:
    group.id: connect-cluster
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  tls:
    trustedCertificates:
      - secretName: kafka-connect-ca-cert
        certificate: ca.crt
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.9.0
  replicas: 1
  bootstrapServers: kafka-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: tazul96/kafka-connect-custom:latest
      pushSecret: dockerhub-secret
    plugins:
      - name: debezium-mongodb-connector
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-mongodb/3.0.6.Final/debezium-connector-mongodb-3.0.6.Final.jar
      - name: mongodb-connector
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.15.0/mongo-kafka-connect-1.15.0.jar
      - name: mongodb-sink-connector
        artifacts:
          - type: jar
            url: https://repo1.maven.org/maven2/org/mongodb/kafka/mongo-kafka-connect/1.14.0/mongo-kafka-connect-1.14.0.jar
      - name: postgresql-connector
        artifacts:
          - type: jar
            url: https://jdbc.postgresql.org/download/postgresql-42.7.5.jar
  config:
    rest.advertised.host.name: "0.0.0.0"
    group.id: connect-cluster
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    security.protocol: PLAINTEXT
  template:
    connectContainer:
      env:
        - name: KAFKA_OPTS
          value: "--add-opens=java.base/java.nio=ALL-UNNAMED"
  readinessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5
