apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9093  # SSL/TLS port
        env:
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL
          value: "SSL"
        - name: KAFKA_LISTENERS
          value: "SSL://0.0.0.0:9093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "SSL://212.28.184.129:9093"
        - name: KAFKA_LISTENER_NAMES
          value: "SSL"
        - name: KAFKA_SSL_KEYSTORE_LOCATION
          value: "/etc/kafka/secrets/kafka.keystore.jks"
        - name: KAFKA_SSL_KEYSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-ssl-certificates
              key: password
        - name: KAFKA_SSL_TRUSTSTORE_LOCATION
          value: "/etc/kafka/secrets/kafka.truststore.jks"
        - name: KAFKA_SSL_TRUSTSTORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-ssl-certificates
              key: password
        volumeMounts:
        - name: ssl-certificates
          mountPath: /etc/kafka/secrets
          readOnly: true
      volumes:
      - name: ssl-certificates
        secret:
          secretName: kafka-ssl-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    app: kafka


--- #another with some changes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "INTERNAL://kafka.kafka.svc.cluster.local:9092,EXTERNAL://212.28.184.129:9093"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx1G -Xms512M"
            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"
            - name: KAFKA_LOG_RETENTION_HOURS
              value: "72" # Retain logs for 3 days
            - name: KAFKA_LOG_SEGMENT_BYTES
              value: "1073741824" # 1 GB per log segment
            - name: KAFKA_LOG_RETENTION_BYTES
              value: "25737418240" # 25 GB total log size
            - name: KAFKA_MAX_MESSAGE_BYTES
              value: "10485760" # 10 MB max message size
          volumeMounts:
            - name: kafka-data
              mountPath: /data
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: kafka-logs
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
    - port: 9092
      targetPort: 9092
      name: internal
    - port: 9093
      targetPort: 9093
      name: external
  selector:
    app: kafka
