apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pvc
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-pvc
spec:
  accessModes:
    - ReadWriteMany #ReadWriteOnce dewa jay
  resources:
    requests:
      storage: 10Gi
