apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        ports:
        - containerPort: 2181
        env:
        - name: ALLOW_ANONYMOUS_LOGIN
          value: "yes"
        # env:
        # - name: ZOO_ENABLE_AUTH
        #   value: "yes"
        # - name: ZOO_ADMIN_USER
        #   value: "admin"
        # - name: ZOO_ADMIN_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: zookeeper-auth-secrets
        #       key: password
        volumeMounts:
        - name: zookeeper-data
          mountPath: /data
        - name: zookeeper-logs
          mountPath: /data-log
      volumes:
      - name: zookeeper-data
        persistentVolumeClaim:
          claimName: zookeeper-data
      - name: zookeeper-logs
        persistentVolumeClaim:
          claimName: zookeeper-logs
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: zookeeper
  type: ClusterIP
